version: 2.1

# Prerequisite
# Make sure you set secret enviroment variables in CICD
# DOCKER_USERNAME
# DOCKER_PASSWORD
# API_TOKEN

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          bash ./build.sh

workflows:
  build:
    jobs:
      - build:
          name: build
